name: shelf_html
version: 0.2.1+1
author: George Moschovitis <george.moschovitis@gmail.com>
description: An adapter for using Shelf to organize client-side applications.
homepage: https://github.com/gmosx/shelf_html
documentation: https://github.com/gmosx/shelf_html/blob/master/README.md
dependencies:
  shelf: '>=0.5.1+1 <0.6.0'
  stack_trace: '>=0.9.3+1 <0.10.0'
dev_dependencies:
  unittest: any
